version: "3"
services:
  main:
    build:
      context: ../
      dockerfile: Dockerfile
    image: "${SERVICE_NAME}:latest"
    container_name: "${SERVICE_NAME}"
    ports:
      - "${DEV_DOCKER_SERVICE_PORT-8000}:80"
      - "${DEV_DOCKER_DEBUG_PORT-8100}:${DEV_DOCKER_DEBUG_PORT-8100}"
    restart: ${DEV_DOCKER_AUTO_RESTART}
    # command: ${DOCKER_CMD}
    command: "bash ./wait-for-it.sh mysql:3306 -t 0 -s -- ${DOCKER_CMD}"
    environment:
      - NO_LISTEN=${NO_LISTEN-no}
      - NODE_ENV=${NODE_ENV-development}
      - PORT=80
    volumes:
      # Keep tracking of these files for development
      - ./wait-for-it.sh:/service/wait-for-it.sh
      - ../.env:/service/.env
      # File access in mounted volumes extremely slow, CPU bound
      #     see https://docs.docker.com/docker-for-mac/osxfs-caching/
      # - ../build:/service/build
      - ../server:/service/server
      # - ../node_modules:/tmp/dependencies/node_modules
      - ../package.json:/service/package.json
      - ../ava.config.js:/service/ava.config.js
    depends_on:
      - "redis"
      - "mongoimport"
      - "mysql"
  redis:
    image: "redis:latest"
    container_name: "${SERVICE_NAME}-redis"
    ports:
      - "${DEV_DOCKER_REDIS_PORT-6379}:6379"
  mongo:
    image: "mongo"
    container_name: "${SERVICE_NAME}-mongo"
    ports:
      - "${DEV_DOCKER_MONGO_PORT-27017}:27017"
  mongoimport:
    build:
      context: ../
      dockerfile: docker/Dockerfile-mongoimport
    image: "${SERVICE_NAME}-mongoimport:latest"
    container_name: "${SERVICE_NAME}-mongoimport"
    depends_on:
      - "mongo"
  mysql:
    image: "mysql:5.6"
    container_name: "${SERVICE_NAME}-mysql"
    ports:
      - "${DEV_DOCKER_MYSQL_PORT-3306}:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=default
    volumes:
      - ./mysql.cnf:/etc/mysql/conf.d/encoding.cnf
      - ../import/mysql:/docker-entrypoint-initdb.d
